print("==mengisi biodata mahasiswa==")
print()

nama= input ('silahkan masukkan nama anda=')
umur = int(input('silahkan masukkan umur kalian='))
asal_sekolah = input('masukkan asal sekolah anda')
alamat= input ('masukkan alamat kalian')
tempatdantanggallahir= input ('masukkan tempat dan tanggal lahir kalian')
tinggibadan = input('masukkan tinggi badan mu')
beratbadan = input ('masukkan berat badan mu')
agama = input ('masukkan agama mu')
jenis_kelamin = input ('masukkan jenis kelamin')
E_mail = input ('masukkan email mu')

print('=='*10)
print('selamat datang',nama)
print('berapa umur mu=',umur)
print('selamat datang',asalsekolah)
print('selamat datang',alamat)
print('selamat datang', tempatdantanggal_lahir)
print('selamat datang',tinggibadan)
print('selamat datang',beratbadan)
print('selamat datang',agama)
print('selamat datang',jeniskelamin)
print('selamat datang',email)
print('=='*10)